# Generated by Django 5.2 on 2025-06-05 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='cloudinary_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
